#
# Autogenerated by ElasticSearch::Transport::ThriftBackend::Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
package ElasticSearch::Transport::ThriftBackend::Constants;
require 5.6.0;
use strict;
use warnings;
use ElasticSearch::Transport::ThriftBackend::Thrift;


1;

__END__
=pod

=head1 NAME

ElasticSearch::Transport::ThriftBackend::Constants

=head1 VERSION

version 0.01

=head1 AUTHOR

Clinton Gormley <drtech@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2011 by Clinton Gormley.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut

